spring:
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password: password
    driverClassName: org.h2.Driver

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

stock-handler:
  import:
    products:
      path: /Users/oscarHome/products.json
    inventories:
      path: /Users/oscarHome/inventory.json
