SET
REFERENTIAL_INTEGRITY false;

DROP TABLE product_contains_article_entity;
DROP TABLE article_entity;
DROP TABLE product_entity;

create table article_entity
(
    id    integer not null,
    name  varchar(255),
    stock integer not null,
    primary key (id)
);

create table product_contains_article_entity
(
    id         integer generated by default as identity,
    amount_of  integer not null,
    article_id integer,
    product_id integer,
    primary key (id)
);

create table product_entity
(
    id   integer generated by default as identity,
    name varchar(255),
    primary key (id)
);

alter table product_contains_article_entity
    add constraint product_contains_article_entity_fk_article_entity
        foreign key (article_id)
            references article_entity;

alter table product_contains_article_entity
    add constraint product_contains_article_entity_fk_product_entity
        foreign key (product_id)
            references product_entity;

SET
REFERENTIAL_INTEGRITY true;